### ISSUE TITLE
Inputs on port 145 and higher

### ISSUE THREAD

**Issue by irek74** [majektom/node-red-contrib-satel-integra-integration#12]
Hi,

first of all, thank you so much for your software. Works great, but I've a small problem: there are 4 PIRs outside of my house and I want to use them to switch on external lights after sunset. I've Satel Integra 256 Plus and I'm not able to read state of inputs on ports higher than 128, and my PIRs are connected to ports 145 and higher. The same problem has domoticz. Home Assistant is able to read status of my external PIRs, but this software has its own (a different) issues. I'm not sure, but it may be related to the size of array of results. If you can check this, I'll appreciate it.

Regards
Irek

**Comment by majektom** [comment]
Hi,

I released version 1.3.0 which supports relevant zones and outputs status requests in the 256-long mode. In order to use this mode, you have to suffix the topic of the request with `_256`. So for example, instead of sending `zones_violation` command to read the zones violation state, send `zones_violation_256` command. It should make your device send back the states of all 256 zones. You can find out which commands support this mode from the `satel-integra-encoder` node's documentation.

Note, I only tested that the device answers these commands with 256 flags. I didn't test if the states on positions higher then 127 are correct because I don't have a device that has more then 128 inputs. I would be grateful if you test it on your device and give me a feedback if it actually works.

Regards,
Tomasz

**Comment by irek74** [comment]
Hi Tomasz.
I've made the tests according to your directions and it works!!!!!!!!!
I've a special external PIRs to protect a space around my house (see the picture) and finally I can use them to turn on and off external lights after sunset (not only for security purpose). You don't even know how much I appreciate your effort.
Thank you so much!

Regards

Irek
![IMG_6427](https://user-images.githubusercontent.com/58270236/141870587-d8550d1b-ddac-4edb-a10d-cca5f48d54c3.jpg)
